--INSERT INTO ARTICLE(title, content) VALUES('111', '111');
--INSERT INTO ARTICLE(title, content) VALUES('222', '222');
--INSERT INTO ARTICLE(title, content) VALUES('333', '333');
--INSERT INTO ARTICLE(title, content) VALUES('나의 최애는?', 'ㄱㄱㄱ');
--INSERT INTO ARTICLE(title, content) VALUES('나의 인생 언어는?', '댓 ㄱㄱ');
--INSERT INTO ARTICLE(title, content) VALUES('나의 장점은?', '대댓 ㄱㄱ');
--
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(4, 'Carten', '파워레인저');
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(4, 'Aiden', '심형래');
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(4, 'Anna', '피카츄');
--
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(5, 'Aiden', '아프리카어');
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(5, 'James', 'c++');
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(5, 'Rora', '씨샵');
--
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(6, 'Rora', '청소잘함');
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(6, 'Carten', '야근잘함');
--INSERT INTO COMMENT(article_id, nickname, body) VALUES(6, 'Aiden', '롤 잘함');