apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kopo11/myapp-mysql:TAG-04c05ee
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service-name.mysql-namespace.svc.cluster.local:3306/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: springuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: springpass
