apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kopo11/myapp-mysql:TAG-db0e850
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/springdb?serverTimezone=Asia/Seoul&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: springuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: springpass
