#git checkout manifest
#  # 파일 수정
#git add k8s/deployment.yaml
#git commit -m "수정 내용"
#git push origin manifest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kopo11/myapp-mysql:latest
          ports:
            - containerPort: 8080


